require 'net/http'
require 'uri'
require 'json'

# Phase 5 — Email Outreach via Resend API.
# Sends personalized storm damage outreach with Gamma report link.
# CC's amy@restorationgc.net for follow-up scheduling.
class ResendEmailService
  API_URL = 'https://api.resend.com/emails'.freeze
  FROM    = 'Michael Johnson <michael@restorationgc.net>'.freeze
  CC      = ['amy@restorationgc.net'].freeze

  SENDER_NAME    = 'Michael Johnson'.freeze
  SENDER_TITLE   = 'Director of Commercial Services'.freeze
  SENDER_COMPANY = 'Restoration GC'.freeze
  SENDER_PHONE   = '(512) 621-4201'.freeze

  # Sends an AI-composed email (subject + body already generated by Claude).
  # Returns { success:, message_id:, error: }.
  def self.send_composed(to:, subject:, body_text:, body_html: nil)
    api_key = ENV['RESEND_API_KEY']
    raise 'RESEND_API_KEY not set' unless api_key

    html = body_html || plain_to_html(body_text)
    payload = {
      from:    FROM,
      to:      Array(to),
      cc:      CC,
      subject: subject,
      html:    html,
      text:    body_text
    }

    response = post_json(payload, api_key)
    if response && response['id']
      { success: true, message_id: response['id'] }
    else
      { success: false, error: response.inspect }
    end
  rescue StandardError => e
    { success: false, error: e.message }
  end

  # Sends a single outreach email. Returns { success:, message_id:, error: }.
  def self.send_outreach(to:, lead:, report_url:, variant: 'a')
    api_key = ENV['RESEND_API_KEY']
    raise 'RESEND_API_KEY not set' unless api_key

    subject = build_subject(lead, variant)
    html    = build_html(lead, report_url, variant: variant)

    payload = {
      from:    FROM,
      to:      Array(to),
      cc:      CC,
      subject: subject,
      html:    html
    }

    response = post_json(payload, api_key)
    if response && response['id']
      { success: true, message_id: response['id'] }
    else
      { success: false, error: response.inspect }
    end
  rescue StandardError => e
    { success: false, error: e.message }
  end

  SENDER_YEARS       = 22
  SENDER_AVG_RETURN  = '780%'

  LEGAL_PARTNER_NAME = 'The Voss Law Firm, P.C.'.freeze
  LEGAL_PARTNER_WEB  = 'www.DeniedClaim.com'.freeze

  # Variant subject lines for A/B/C/D/E/F/G testing
  SUBJECT_VARIANTS = {
    'a' => 'Confidential: Storm Damage Intelligence Report — %<address>s',
    'b' => 'Urgent: Hidden Hail Damage Risk at %<address>s',
    'c' => 'Forensic Assessment Ready — %<address>s [%<date>s Storm]',
    'd' => '%<owner>s — Your %<address>s Property Was in the Hail Swath',
    'e' => '%<owner>s — The Garden Ridge Founder Was Skeptical Too',
    'f' => '%<owner>s — The State of Texas Had the Same Roof Problem',
    'g' => '%<owner>s — Carrier Said $0. We Got Them $5.4 Million.'
  }.freeze

  # Verified client case studies — signed reference letters on file
  TESTIMONIALS = {
    garden_ridge: {
      client:    'Eric W. White, Founder & CEO — Garden Ridge Pottery',
      location:  'Schertz, TX',
      sector:    'commercial',
      situation: 'Unaware buildings had sustained hail damage. Initially skeptical.',
      carrier:   'Claim disputed by carrier',
      recovery:  '$4.2 million',
      quote:     'After showing us the map of the storm, we gave Mr. Johnson permission to inspect. ' \
                 'To our surprise, the roofs, wall panels, and AC units were all heavily damaged by hail. ' \
                 'After meeting with our insurance company\'s adjuster, Mr. Johnson was able to get us ' \
                 'over four million dollars to repair the damage.',
      signatory: 'Eric W. White, Founder/CEO, Garden Ridge Pottery'
    },
    region_13: {
      client:    'Luke Martin, Executive Director — Texas Education Service Center Region 13',
      location:  'Austin, TX (State of Texas)',
      sector:    'government / education',
      situation: 'Active roof leaks — staff scrambled with tarps to protect equipment every time it rained. ' \
                 'Underlying hail damage was undetected. Carrier denied the claim outright.',
      carrier:   'Denied outright',
      recovery:  '$800,000+',
      quote:     'Thanks to Michael we received $1.2 million from hail damage we were unaware of. ' \
                 'Large insurance claims can feel daunting at times. Thanks to Michael\'s years of experience ' \
                 'he was able to tell us ahead of time what was going to happen and why — and he was right every time.',
      signatory: 'Luke Martin, Executive Director, Texas Education Service Center Region 13'
    }
  }.freeze

  private

  def self.build_subject(lead, variant)
    template = SUBJECT_VARIANTS.fetch(variant.to_s, SUBJECT_VARIANTS['a'])
    format(template,
           address: lead[:address],
           owner:   lead[:human_owner_name]&.split&.first || 'Sir/Madam',
           date:    lead[:storm_date] || Date.today.strftime('%b %-d'))
  end

  def self.build_html(lead, report_url, variant: 'a')
    case variant.to_s
    when 'e' then build_html_garden_ridge(lead, report_url)
    when 'f' then build_html_region_13(lead, report_url)
    when 'g' then build_html_voss_denied(lead, report_url)
    else          build_html_standard(lead, report_url)
    end
  end

  # Variant E — Garden Ridge story lead (commercial targets)
  def self.build_html_garden_ridge(lead, report_url)
    first_name = lead[:human_owner_name]&.split&.first || 'there'
    address    = lead[:address]
    t          = TESTIMONIALS[:garden_ridge]

    <<~HTML
      <div style="font-family: Arial, sans-serif; max-width: 640px; margin: auto; color: #222; line-height: 1.6;">
        <p>Hi #{first_name},</p>

        <p>When we first approached Eric White — the founder of Garden Ridge — about a potential
        hail claim on his original Schertz, TX stores, he was skeptical. He didn't think he had
        a claim. His buildings looked fine.</p>

        <p>We showed him the storm map. He let us inspect. The roofs, wall panels, and AC units
        were all heavily damaged. <strong>His carrier paid #{t[:recovery]}.</strong></p>

        <p>I'm reaching out because <strong>#{address}</strong> was in the documented path of the
        same type of storm event — and in my experience, the properties that look fine from the
        ground are often the ones sitting on the largest undetected claims.</p>

        <p>We've prepared a confidential damage intelligence report for your property:</p>

        <p style="text-align:center; margin: 32px 0;">
          <a href="#{report_url}"
             style="background-color:#c0392b; color:white; padding:14px 28px;
                    text-decoration:none; border-radius:4px; font-weight:bold; font-size:16px;">
            View Your Confidential Property Report &rarr;
          </a>
        </p>

        <p>There's no obligation. Eric White's signed reference letter is available upon request.</p>

        <p>Amy on my team will reach out within 24 hours to find a time that works.</p>

        <p>Best regards,</p>
        <p>
          <strong>#{SENDER_NAME}</strong><br>
          #{SENDER_TITLE}<br>
          #{SENDER_COMPANY}<br>
          #{SENDER_PHONE}
        </p>
      </div>
    HTML
  end

  # Variant F — Region 13 / State of Texas story lead (public sector / education targets)
  def self.build_html_region_13(lead, report_url)
    first_name = lead[:human_owner_name]&.split&.first || 'there'
    address    = lead[:address]
    t          = TESTIMONIALS[:region_13]

    <<~HTML
      <div style="font-family: Arial, sans-serif; max-width: 640px; margin: auto; color: #222; line-height: 1.6;">
        <p>Hi #{first_name},</p>

        <p>The Texas Education Service Center Region 13 — where teachers from across the state
        come for continuing education — had a roof problem everyone could see: every time it rained,
        the entire staff dropped what they were doing to cover up millions of dollars of equipment
        with tarps.</p>

        <p>What they couldn't see was the hail damage underneath. Their carrier denied the claim
        outright. <strong>We got them #{t[:recovery]}.</strong></p>

        <p>Executive Director Luke Martin's signed letter is on file. He said Michael
        &ldquo;was able to tell us ahead of time what was going to happen and why — and he was
        right every time.&rdquo;</p>

        <p>I'm reaching out because <strong>#{address}</strong> was in the documented path of a
        significant hail event — and carrier denials on public-sector properties are more common
        than most facilities directors realize.</p>

        <p>We've prepared a confidential damage intelligence report for your property:</p>

        <p style="text-align:center; margin: 32px 0;">
          <a href="#{report_url}"
             style="background-color:#1a3a6b; color:white; padding:14px 28px;
                    text-decoration:none; border-radius:4px; font-weight:bold; font-size:16px;">
            View Your Confidential Property Report &rarr;
          </a>
        </p>

        <p>There's no cost and no obligation. Amy on my team will reach out within 24 hours
        to schedule a call at your convenience.</p>

        <p>Best regards,</p>
        <p>
          <strong>#{SENDER_NAME}</strong><br>
          #{SENDER_TITLE}<br>
          #{SENDER_COMPANY}<br>
          #{SENDER_PHONE}
        </p>
      </div>
    HTML
  end

  # Variant G — Voss Law "denied claim" angle (any commercial target where denial is the fear)
  # Uses the $5.4M Industrial Property case as the hook — $75K offer → $5.4M recovery
  def self.build_html_voss_denied(lead, report_url)
    first_name = lead[:human_owner_name]&.split&.first || 'there'
    address    = lead[:address]

    <<~HTML
      <div style="font-family: Arial, sans-serif; max-width: 640px; margin: auto; color: #222; line-height: 1.6;">
        <p>Hi #{first_name},</p>

        <p>An industrial property owner in Texas received a check from his insurance carrier.
        <strong>$75,000.</strong> The carrier called it settled.</p>

        <p>He wasn't sure it was right, so he called us. We brought in The Voss Law Firm —
        Commercial Policyholder Attorneys. The actual settlement: <strong>$5,400,000.</strong></p>

        <p>The carrier had offered him 1.4 cents on the dollar.</p>

        <p>I'm reaching out because <strong>#{address}</strong> was in the path of a documented
        hail event — and in #{SENDER_YEARS} years of large-loss commercial work, I've learned
        that what the carrier offers first and what a property is actually worth are rarely
        the same number. Voss Law publishes data showing clients recover up to
        <strong>#{SENDER_AVG_RETURN} more</strong> than the carrier's initial offer once
        legal representation is in place.</p>

        <p>We've prepared a confidential damage intelligence report for your property.
        There is no cost and no obligation:</p>

        <p style="text-align:center; margin: 32px 0;">
          <a href="#{report_url}"
             style="background-color:#c0392b; color:white; padding:14px 28px;
                    text-decoration:none; border-radius:4px; font-weight:bold; font-size:16px;">
            View Your Confidential Property Report &rarr;
          </a>
        </p>

        <p>Amy on my team will reach out within 24 hours to schedule a brief call at your convenience.</p>

        <p>Best regards,</p>
        <p>
          <strong>#{SENDER_NAME}</strong><br>
          #{SENDER_TITLE}<br>
          #{SENDER_COMPANY}<br>
          #{SENDER_PHONE}
        </p>
        <p style="font-size:12px; color:#666;">
          Working alongside #{LEGAL_PARTNER_NAME} — Commercial Policyholder Attorneys.
          No fee if no recovery. #{LEGAL_PARTNER_WEB}
        </p>
      </div>
    HTML
  end

  def self.build_html_standard(lead, report_url)
    first_name   = lead[:human_owner_name]&.split&.first || 'there'
    hail_size    = lead[:hail_size] || '1.75'
    county       = lead[:county]    || 'your county'
    storm_date   = lead[:storm_date] || 'recently'
    address      = lead[:address]
    title        = lead[:owner_title]
    parent_co    = lead[:parent_company]
    context_line = title && parent_co ? "As #{title} of #{parent_co}, you understand" : "As a commercial property owner, you understand"

    <<~HTML
      <div style="font-family: Arial, sans-serif; max-width: 640px; margin: auto; color: #222;">
        <p>Hi #{first_name},</p>

        <p>On #{storm_date}, a significant hail storm tracking #{hail_size}&rdquo; stones swept through #{county} County, placing
        <strong>#{address}</strong> directly within the documented hail swath.</p>

        <p>#{context_line} that undocumented storm damage represents both a liability concern
        <em>and</em> a strategic capital improvement opportunity — but only when identified before carrier deadlines close.</p>

        <p>Our forensic team has prepared a property-specific damage intelligence report:</p>

        <p style="text-align:center; margin: 32px 0;">
          <a href="#{report_url}"
             style="background-color:#c0392b; color:white; padding:14px 28px;
                    text-decoration:none; border-radius:4px; font-weight:bold; font-size:16px;">
            View Confidential Property Report &rarr;
          </a>
        </p>

        <p>Amy on my team will reach out within 24 hours to schedule a 20-minute call at a time that works for you.
        There is no obligation — just enterprise-grade forensic clarity on your exposure.</p>

        <p>Best regards,</p>
        <p>
          <strong>#{SENDER_NAME}</strong><br>
          #{SENDER_TITLE}<br>
          #{SENDER_COMPANY}<br>
          #{SENDER_PHONE}
        </p>
      </div>
    HTML
  end

  def self.plain_to_html(text)
    # Wrap plain text in minimal HTML preserving line breaks
    escaped = text.gsub('&', '&amp;').gsub('<', '&lt;').gsub('>', '&gt;')
    paragraphs = escaped.split(/\n{2,}/).map { |p| "<p>#{p.gsub("\n", '<br>')}</p>" }.join("\n")
    "<div style=\"font-family:Arial,sans-serif;max-width:600px;color:#222;line-height:1.6;\">#{paragraphs}</div>"
  end

  def self.post_json(payload, api_key)
    uri  = URI.parse(API_URL)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    req = Net::HTTP::Post.new(uri.path)
    req['Authorization'] = "Bearer #{api_key}"
    req['Content-Type']  = 'application/json'
    req.body = payload.to_json
    resp = http.request(req)
    JSON.parse(resp.body)
  end
end
