# Generated by Django 5.2.17 on 2026-09-15 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyResearchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_runs",
                        to="matching.target",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("complaint", "Tenant/public complaint"),
                            ("permit", "Building permit or code violation"),
                            ("damage", "Reported damage or storm event"),
                            ("news", "Business/entity news"),
                            ("litigation", "Litigation or regulatory action"),
                            ("other", "Other property/entity fact"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Factual, property/entity-level summary of what was found"
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateField(blank=True, null=True)),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="0-100, how relevant this is to a hail-damage claim",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="matching.target",
                    ),
                ),
                (
                    "research_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="matching.propertyresearchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
    ]
