# Generated by Django 5.2.17 on 2026-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_propertyresearchrun_propertyfinding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactimport",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn export"),
                    ("facebook", "Facebook friends export"),
                    ("phone", "Phone contacts export"),
                    ("email", "Email address book export"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
