# Generated by Django 5.2.17 on 2026-09-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_alter_contactimport_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="ticker",
            field=models.CharField(
                blank=True,
                help_text="Stock ticker, only if the owning entity is a public company (e.g. a REIT). Leave blank for private LLCs -- enables SEC filings research when set.",
                max_length=10,
            ),
        ),
    ]
