# Generated by Django 5.2.17 on 2026-09-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0004_target_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Owner's direct email, if known -- for reaching them without a warm path",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Owner's direct phone, if known -- for reaching them without a warm path",
                max_length=50,
            ),
        ),
    ]
