insert into public.compliance_rules (rule_key,scope_state,rule_type,pattern,is_regex,severity,message,suggested_rewrite,citation_url) values
('us_no_guarantee','OTHER','pattern','\b(guarantee|guaranteed|we guarantee|100%|full payout|we get you paid)\b',true,'block','Outcome guarantee prohibited (misleading claim).','We help document your loss so the claim is evaluated fairly.','https://www.ftc.gov/legal-library/browse/rules/can-spam-rule'),
('us_no_legal_advice','OTHER','pattern','\b(you have a bad faith case|you should sue|legal advice|we will file suit for you)\b',true,'block','No legal advice — refer to counsel.','An attorney can advise you on legal options.',null),
('us_no_adjusting','OTHER','pattern','\b(we adjust your claim|we negotiate with your insurer|act as your adjuster|maximize your settlement)\b',true,'block','Unauthorized public adjusting language.','We document damage and scope; a licensed public adjuster or your attorney handles negotiation.','https://law.justia.com/cases/texas/supreme-court/2024/22-0427.html'),
('tx_no_deductible','TX','pattern','\b(waive|absorb|rebate|cover|eat|pay your|no) ?deductible\b',true,'block','TX HB2102/§707.002 — cannot waive/absorb deductible.','Texas law requires you to pay your deductible; we help you plan for it.','https://www.tdi.texas.gov/consumer/storms/roofing-and-insurance-know-the-law.html'),
('tx_contract_notice','TX','required_disclaimer','Texas law requires a person insured under a property insurance policy to pay any deductible applicable to a claim made under the policy...',false,'block','TX Bus & Com §27.02(b) 12pt boldface notice required on $1000+ insurance-proceeds contracts.',null,'https://statutes.capitol.texas.gov/Docs/BC/htm/BC.27.htm'),
('tx_disclaimer','TX','required_disclaimer','Restoration GC is a licensed general contractor, not a public insurance adjuster, and does not adjust claims or provide legal advice (Tex. Ins. Code §4102.163).',false,'warn','Attach TX educational disclaimer.',null,'https://statutes.capitol.texas.gov/Docs/IN/htm/IN.4102.htm'),
('fl_deadline_disclaimer','FL','required_disclaimer','In Florida, notice of a new or reopened property claim is generally barred after 1 year from the date of loss (Fla. Stat. §627.70132).',false,'warn','Attach FL deadline disclaimer.',null,'https://www.flsenate.gov/laws/statutes/2022/627.70132'),
('ok_notice','OK','required_disclaimer','Oklahoma law (59 O.S. §1151.30) requires this written notification: a roofing contractor may not pay any part of your deductible.',false,'block','OK §1151.30 written notification required with initial estimate.',null,'https://law.justia.com/codes/oklahoma/title-59/section-59-1151-30/'),
('ok_no_deductible','OK','pattern','\b(waive|absorb|rebate|cover|eat|pay your|no) ?deductible\b',true,'block','OK 59 O.S. §1151.30 (HB 1940) — roofing contractor may not advertise/promise to pay any part of the deductible.','Oklahoma law prohibits a roofing contractor from paying any part of your deductible; we help you plan for it.','https://law.justia.com/codes/oklahoma/title-59/section-59-1151-30/'),
('il_no_pa_referral','IL','pattern','\b(our public adjuster|we refer you to a public adjuster|paid referral)\b',true,'block','IL Bulletin 2026-02 — paid PA lead-gen requires PA license; avoid referral model in IL.','We document damage; you may independently choose a licensed public adjuster or attorney.','https://idoi.illinois.gov/content/dam/soi/en/web/insurance/companies/companybulletins/cb2026-02-public-adjuster-lead-generation-01-26-26-arg.pdf'),
('il_no_deductible','IL','pattern','\b(waive|absorb|inflate).{0,15}deductible\b',true,'block','IL 215 ILCS 5/155.51 / PA 098-0862 — deductible fraud prohibited.','Illinois law requires you to pay your deductible.','https://www.ilga.gov/legislation/ilcs/');
